services:
  gossipnet1:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'go run main.go --bind 7000 --name starting'
    ports:
      - '7000:7000/udp'
      - '7000:7000/tcp'
      - '5353:5353'
    networks:
      - my_network
  gossipnet2:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'go run main.go --bind 7018 --peer gossipnet1:7000 --name second --config-file config2.json'
    ports:
      - '7018:7018/udp'
      - '7018:7018/tcp'
      - '5354:5353'
    depends_on:
      - gossipnet1
    networks:
      - my_network

networks:
  my_network:
