services:
  gossipnet1:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'go run main.go --bind 7000 --name starting --config-file config1.json --dnsAddr 127.0.0.1:53'
    ports:
      - '7000:7000/udp'
      - '7000:7000/tcp'
      - '5354:5354/udp'
      - '5354:5354/tcp'
    networks:
      - my_network
    volumes:
      - .:/go/src/app
  gossipnet2:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'go run main.go --bind 7018 --peer gossipnet1:7000 --name second --config-file config2.json --dnsAddr 127.0.0.1:53'
    ports:
      - '7018:7018/udp'
      - '7018:7018/tcp'
      # - '5354:5353'
    depends_on:
      - gossipnet1
    networks:
      - my_network
    volumes:
      - .:/go/src/app

networks:
  my_network:
